### ISSUE TITLE
Document CLI

### ISSUE THREAD

**Issue by rr-** [spillerrec/Overmix#106]
Running `./OvermixCli ~/somewhere/*.jpg` doesn't create any output files in both `./` and `~/somewhere/`. So I run `./OvermixCli --help` to figure out how to use it... but the output from it doesn't help at all (just lists some switches without description). The users are on their own and need to dive into sources. There are no man pages either.

**Comment by spillerrec** [comment]
I have expanded the help text a bit more, and added sub-pages for the different commands. Are you able to compile to check it out and see if it is enough to understand it?
Note that I'm currently changing where the align algorithms are configured, so you can't currently change much with them.

**Comment by rr-** [comment]
Yes, much better, thanks!
