### ISSUE TITLE
error on ubuntu installation

### ISSUE THREAD

**Issue by rachmadaniHaryono** [spillerrec/Overmix#113]
hi, im trying to install the program on ubuntu 17.10 64 bit.

i have installed the package required similar to `before_section` on travis.yml, with exception `libxcb-util0-dev` package, which replaced by `libxcb-util-dev`

after that i got this error when running `make` command

```bash
[ 69%] Building CXX object interface/CMakeFiles/Overmix.dir/gui/visualisations/MovementGraph.cpp.o
In file included from /home/user/git/Overmix/interface/gui/visualisations/MovementGraph.cpp:21:0:
/usr/include/qcustomplot.h:54:12: fatal error: QtPrintSupport: No such file or directory
 #  include <QtPrintSupport>
            ^~~~~~~~~~~~~~~~
compilation terminated.
interface/CMakeFiles/Overmix.dir/build.make:326: recipe for target 'interface/CMakeFiles/Overmix.dir/gui/visualisations/MovementGraph.cpp.o' failed
make[2]: *** [interface/CMakeFiles/Overmix.dir/gui/visualisations/MovementGraph.cpp.o] Error 1
CMakeFiles/Makefile2:234: recipe for target 'interface/CMakeFiles/Overmix.dir/all' failed
make[1]: *** [interface/CMakeFiles/Overmix.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```
simple googling only found answer such as this, which i think not related to problem

https://stackoverflow.com/questions/19145763/qt-cannot-open-include-file-qprinter

**Comment by spillerrec** [comment]
I don't use Ubuntu so I'm not too sure about which packages you need to have, the Travis configuration is for a very old version of Ubuntu. However I would believe that CMake should have complained during the configuration step if you were missing QtPrintSupport. It should be included in `qtbase5-dev` though. Do you have a `/qt5/QtPrintSupport/QtPrintSupport` file somewhere in `/include/` ?

**Comment by rachmadaniHaryono** [comment]
you mean `/usr/include`? no. there is also no `qt5` folder there

i also check `qtbase5-deb` and it is installed

```bash
qtbase5-dev is already the newest version (5.9.1+dfsg-10ubuntu1).
```

**Comment by spillerrec** [comment]
Yes, I meant `/usr/include`. You should have a `qt5` folder as otherwise it would have failed a lot earlier, but it might be in a sub-directory like `x86_64-linux-gnu` depending on your CPU architecture.
If it is there, could you share the output of CMake when you generate the makefiles?

Now that I take a closer look at the travis file I notice I have manually added the path to QtPrintSupport:
```
CXXFLAGS=-isystem\ /usr/include/qt5/QtPrintSupport cmake ..  -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=release
```
that is the `CXXFLAGS=-isystem\ /usr/include/qt5/QtPrintSupport` part. You would obviously need to change the path to where it is on your system.
This shouldn't be needed as CMake is supposed to find it by itself, so this was probably just a quick-fix as I didn't have access to an Ubuntu machine while setting up Travis either...

**Comment by rachmadaniHaryono** [comment]
first: yes, there is `/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport`

so based on your suggestion i run another cmake command

```bash
CXXFLAGS=-isystem\ /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport cmake .. -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=release
```

but this got another error

```bash
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/q/git/Overmix/release/CMakeFiles/CMakeOutput.log".
See also "/home/q/git/Overmix/release/CMakeFiles/CMakeError.log".
```

**Comment by spillerrec** [comment]
Remove the `-DCMAKE_CXX_COMPILER=$COMPILER` part, it is something Travis uses to test different compilers. The reset should be fine, assuming you are in the correct directory.

**Comment by rachmadaniHaryono** [comment]
the compile is successful.

i have to delete the release folder and run the cmake again.

i also got this warning

```bash
[ 16%] Building CXX object src/CMakeFiles/OvermixCore.dir/planes/Plane-scaling.cpp.o
/home/user/git/Overmix/src/planes/Plane-scaling.cpp:148:14: warning: ‘Overmix::Plane scale2x(const Overmix::Plane&, int, Overmix::Plane::Filter)’ defined but not used [-Wunused-function]
 static Plane scale2x( const Plane& p, int window, Plane::Filter f ){
              ^~~~~~~
[ 17%] Building CXX object src/CMakeFiles/OvermixCore.dir/planes/Plane-edgedetection.cpp.o
```
but i think it should be ok. the program also run perfectly.

full script to install on ubuntu 17.10 64 bit

```bash
sudo apt-get install -y qtbase5-dev libqcustomplot-dev liblcms2-dev libpugixml-dev libfftw3-dev libjpeg-dev libpng-dev liblzma-dev libqt5x11extras5-dev libboost-dev libeigen3-dev libx11-xcb-dev libxcb-util-dev
mkdir release
cd release
CXXFLAGS=-isystem\ /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport cmake ../ -DCMAKE_BUILD_TYPE=release
make
```

i think this can be closed
