### ISSUE TITLE
Crash on trying to preview images

### ISSUE THREAD

**Issue by Redricks** [spillerrec/Overmix#139]
Crash on trying to preview images, input or ordered output with message 
```
Overmix: cmsxform.c:151: cmsDeleteTransform: Assertion `(p != ((void *)0))' failed.
Aborted (core dumped)
```
Built master on Ubuntu 19.04 x64, 16gb ram

**Comment by spillerrec** [comment]
Commit 08700ffa14384524fecba31b63c565180d2aea8a should fix this (I linked it to the wrong issue) so try to compile from master now.

**Comment by Redricks** [comment]
Everything looks fine now. Thanks.
