### ISSUE TITLE
0.4.0 Alpha 2 crashes upon launching

### ISSUE THREAD

**Issue by jasonTong68** [spillerrec/Overmix#142]
**Describe the bug**
When opening Overmix.exe, the following error message is displayed.
```
This application failed to start because it could not find or load the Qt platform plugin "windows" in "".

Reinstalling the application may fix this problem.
```

After pressing OK, a runtime error is then displayed.
```
Runtime Error!
Program: F:\Overmix.v0.4.0-alpha2.win64\Overmix.exe

This application has request the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

**How To Reproduce**
Download `Overmix.v0.4.0-alpha2.win64.7z` from the latest release. Extract, and run.

**Useful information:**
 - Windows 10 64-bit
 - Overmix version 0.4.0 Alpha 2
 - 8 GB ram

**Comment by spillerrec** [comment]
This is a DLL issue with the GUI library, it fails to load the `platforms/qwindows.dll`. Which is a bit strange, as it seems it have worked for others.
But it does seems like I made a typo, try renaming the folder `platfoms` to `platforms`. I have updated the downloads as well.

**Comment by jasonTong68** [comment]
It works now, many thanks

**Comment by spillerrec** [comment]
Great, feel free to create an issue here if you have any questions on how to use it.
