### ISSUE TITLE
Small line artefacts

### ISSUE THREAD

**Issue by IrreversibleReboot** [spillerrec/Overmix#148]
**Describe the bug**
I'm trying to stitch together anime screenshots but small line artefacts appear on the final image.
![test_screenshot](https://user-images.githubusercontent.com/9488735/71623046-1b5a7780-2bda-11ea-8a8e-67d41687d3e9.png)
I've tried using dump files I obtained using video-dumper, but since the character speaks during the movement, the final result is like this. The artefacts are still here, albeit a lot less visible.
![test_dump](https://user-images.githubusercontent.com/9488735/71623091-65435d80-2bda-11ea-8c10-d760bb7920e6.png)
Removing the frames where her mouth moves seems to fix this, but the lines are still there.
![test_dump2](https://user-images.githubusercontent.com/9488735/71623093-670d2100-2bda-11ea-8d98-83f8d7163329.png)

You can see the lines at the top and bottom on the original screenshots below, so I guess a fix would be to crop those out. I guess those are part of the video file since they also appear on the dump files and on PNG screenshots from mpv. But is there a setting to fix this issue directly in Overmix? I've tried messing around with the settings but I didn't find anything.

**How To Reproduce**
Here are the screenshots, as well as the video file used to dump the dump files.
![1577730290](https://user-images.githubusercontent.com/9488735/71623173-f7e3fc80-2bda-11ea-9d28-a1311adc2207.jpg)
![1577730287](https://user-images.githubusercontent.com/9488735/71623174-f7e3fc80-2bda-11ea-8937-859866fc06fc.jpg)
![1577730284](https://user-images.githubusercontent.com/9488735/71623175-f87c9300-2bda-11ea-9d2c-d7af3dff6c6b.jpg)
https://mega.nz/#!xl0TVaoD!grqyuHf_rAZIRQbXiEjU_Jv7hrfRKdVgNmD1hw8OBww
I've used the default settings for this version.

**Useful information:**
- OS: Arch Linux
- Overmix version 0.4.0 alpha 2 
- RAM: 15GB

**Comment by spillerrec** [comment]
There is a option to crop the images in Overmix. As you noted, it is an issue in the video file and it is actually quite common.

To crop the images, go to the `Files` tap and expand the `Modify files` group by clicking on the checkbox. Select `Crop` in the drop-down menu and click `Add`. After choosing some fitting values, in the `Selection` group click `Apply modifications` to apply the crop. The crop is relative to the current size, so clicking it again will crop the images further.
![overmix-crop](https://user-images.githubusercontent.com/2292170/71623777-41cee180-2bdf-11ea-9a63-fb2b57db6381.png)

For the mouth issue, I don't currently have a good solution for that other than removing those frames. (Select them in the image list and press delete.) Overmix blends information from all the frames which greatly reduces compression artifacts and banding (more important back in the days), but it also causes artifacts when there is movement in the image. My habit is to take the result from using all frames and copying the wanted mouth frame in Gimp for the highest quality, but that is overkill in most cases.
My idea to improve it is to be able to select an area in the image so Overmix can find all the mouth states and generate an image for each, but well, someday...

By the way, the video dumper utility is now included in Overmix, simply drag-and-drop the video file into Overmix. The UI is very much WIP, but it is better than using the CLI tool. It will give an error if it goes pass the end of the file, but you can ignore that, it still works.

**Comment by IrreversibleReboot** [comment]
Ah thank you very much, cropping fixed it!
![test_screenshot_crop](https://user-images.githubusercontent.com/9488735/71643793-1bcc3e80-2cbe-11ea-9e76-201a363b350e.png)
And thanks for specifying how to use the video dumper!

**Comment by spillerrec** [comment]
Great to hear, feel free to create another issue if you have any other questions at some point
