### ISSUE TITLE
Overmix.v0.4.0-alpha3 doesn't support horizontal stitching

### ISSUE THREAD

**Issue by Ryuukishi** [spillerrec/Overmix#156]
alpha3 currently only seems to support stitching images vertically. Would be nice to get a new build to support stitching images in other directions like horizontally and diagonally. 

Also, Merry Christmas!

**Comment by spillerrec** [comment]
It should be supported, however the option has been moved to "Comparing" compared to older versions. Change the "Movement directions" to "Horizontal" and "Both" for horizontal and diagonal stitching:
![image](https://user-images.githubusercontent.com/2292170/147205818-e287ca11-3510-477b-8e3f-6b695d29f9d7.png)

**Comment by Ryuukishi** [comment]
Totally missed it, thanks!
